export const SHOW_CREATE_DIALOG = 'SHOW_CREATE_DIALOG';
export const CANCEL_USER_DIALOG = 'CANCEL_USER_DIALOG';
export const SELECT_USERS = 'SELECT_USERS';
export const CLEAR_USER_SELECTION = 'CLEAR_USER_SELECTION';
export const SHOW_DELETE_DIALOG = 'SHOW_DELETE_DIALOG';
