export const START_ADDING = 'START_ADDING';
export const CANCEL_USER_DIALOG = 'CANCEL_USER_DIALOG';
export const SELECT_USERS = 'SELECT_USERS';
export const CLEAR_USER_SELECTION = 'CLEAR_USER_SELECTION';
